// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"net/netip"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*)
FROM audit_logs
WHERE
    ($1::text IS NULL OR namespace = $1)
    AND ($2::text IS NULL OR user_id = $2)
    AND ($3::text IS NULL OR action = $3)
`

type CountAuditLogsParams struct {
	Namespace *string `json:"namespace"`
	UserID    *string `json:"user_id"`
	Action    *string `json:"action"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs, arg.Namespace, arg.UserID, arg.Action)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
    user_id,
    user_email,
    action,
    namespace,
    resource,
    resource_type,
    result,
    details,
    ip_address
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, user_id, user_email, action, namespace, resource, resource_type, result, details, ip_address, created_at
`

type CreateAuditLogParams struct {
	UserID       string      `json:"user_id"`
	UserEmail    string      `json:"user_email"`
	Action       string      `json:"action"`
	Namespace    *string     `json:"namespace"`
	Resource     *string     `json:"resource"`
	ResourceType *string     `json:"resource_type"`
	Result       string      `json:"result"`
	Details      []byte      `json:"details"`
	IpAddress    *netip.Addr `json:"ip_address"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.UserID,
		arg.UserEmail,
		arg.Action,
		arg.Namespace,
		arg.Resource,
		arg.ResourceType,
		arg.Result,
		arg.Details,
		arg.IpAddress,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserEmail,
		&i.Action,
		&i.Namespace,
		&i.Resource,
		&i.ResourceType,
		&i.Result,
		&i.Details,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, user_id, user_email, action, namespace, resource, resource_type, result, details, ip_address, created_at
FROM audit_logs
WHERE
    ($1::text IS NULL OR namespace = $1)
    AND ($2::text IS NULL OR user_id = $2)
    AND ($3::text IS NULL OR action = $3)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListAuditLogsParams struct {
	Namespace *string `json:"namespace"`
	UserID    *string `json:"user_id"`
	Action    *string `json:"action"`
	Offset    int32   `json:"offset"`
	Limit     int32   `json:"limit"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.Namespace,
		arg.UserID,
		arg.Action,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.Action,
			&i.Namespace,
			&i.Resource,
			&i.ResourceType,
			&i.Result,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
