// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: builds.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBuilds = `-- name: CountBuilds :one
SELECT COUNT(*) FROM builds WHERE repository_id = $1
`

func (q *Queries) CountBuilds(ctx context.Context, repositoryID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBuilds, repositoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBuild = `-- name: CreateBuild :one
INSERT INTO builds (
    repository_id, number, branch, commit_sha, image_tag,
    status, trigger_type, triggered_by, retry_of
)
SELECT
    $1::uuid,
    COALESCE(MAX(number), 0) + 1,
    $2::text,
    $3::text,
    $4::text,
    'pending',
    $5::text,
    $6::text,
    $7::uuid
FROM builds
WHERE repository_id = $1::uuid
RETURNING id, repository_id, number, branch, commit_sha, image_tag, status, trigger_type, triggered_by, job_name, error_message, retry_of, started_at, finished_at, created_at
`

type CreateBuildParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Branch       string      `json:"branch"`
	CommitSha    string      `json:"commit_sha"`
	ImageTag     string      `json:"image_tag"`
	TriggerType  string      `json:"trigger_type"`
	TriggeredBy  string      `json:"triggered_by"`
	RetryOf      pgtype.UUID `json:"retry_of"`
}

// The build number is derived inside the insert rather than read first, so two
// concurrent triggers cannot both compute the same next number.
func (q *Queries) CreateBuild(ctx context.Context, arg CreateBuildParams) (Build, error) {
	row := q.db.QueryRow(ctx, createBuild,
		arg.RepositoryID,
		arg.Branch,
		arg.CommitSha,
		arg.ImageTag,
		arg.TriggerType,
		arg.TriggeredBy,
		arg.RetryOf,
	)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Number,
		&i.Branch,
		&i.CommitSha,
		&i.ImageTag,
		&i.Status,
		&i.TriggerType,
		&i.TriggeredBy,
		&i.JobName,
		&i.ErrorMessage,
		&i.RetryOf,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGitRepository = `-- name: DeleteGitRepository :exec
DELETE FROM git_repositories WHERE project_id = $1 AND name = $2
`

type DeleteGitRepositoryParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
}

func (q *Queries) DeleteGitRepository(ctx context.Context, arg DeleteGitRepositoryParams) error {
	_, err := q.db.Exec(ctx, deleteGitRepository, arg.ProjectID, arg.Name)
	return err
}

const finishBuild = `-- name: FinishBuild :one
UPDATE builds
SET status = $2, error_message = $3, finished_at = NOW()
WHERE id = $1
RETURNING id, repository_id, number, branch, commit_sha, image_tag, status, trigger_type, triggered_by, job_name, error_message, retry_of, started_at, finished_at, created_at
`

type FinishBuildParams struct {
	ID           pgtype.UUID `json:"id"`
	Status       string      `json:"status"`
	ErrorMessage *string     `json:"error_message"`
}

func (q *Queries) FinishBuild(ctx context.Context, arg FinishBuildParams) (Build, error) {
	row := q.db.QueryRow(ctx, finishBuild, arg.ID, arg.Status, arg.ErrorMessage)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Number,
		&i.Branch,
		&i.CommitSha,
		&i.ImageTag,
		&i.Status,
		&i.TriggerType,
		&i.TriggeredBy,
		&i.JobName,
		&i.ErrorMessage,
		&i.RetryOf,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getBuild = `-- name: GetBuild :one
SELECT id, repository_id, number, branch, commit_sha, image_tag, status, trigger_type, triggered_by, job_name, error_message, retry_of, started_at, finished_at, created_at FROM builds WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBuild(ctx context.Context, id pgtype.UUID) (Build, error) {
	row := q.db.QueryRow(ctx, getBuild, id)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Number,
		&i.Branch,
		&i.CommitSha,
		&i.ImageTag,
		&i.Status,
		&i.TriggerType,
		&i.TriggeredBy,
		&i.JobName,
		&i.ErrorMessage,
		&i.RetryOf,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getBuildByNumber = `-- name: GetBuildByNumber :one
SELECT id, repository_id, number, branch, commit_sha, image_tag, status, trigger_type, triggered_by, job_name, error_message, retry_of, started_at, finished_at, created_at FROM builds WHERE repository_id = $1 AND number = $2 LIMIT 1
`

type GetBuildByNumberParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Number       int64       `json:"number"`
}

func (q *Queries) GetBuildByNumber(ctx context.Context, arg GetBuildByNumberParams) (Build, error) {
	row := q.db.QueryRow(ctx, getBuildByNumber, arg.RepositoryID, arg.Number)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Number,
		&i.Branch,
		&i.CommitSha,
		&i.ImageTag,
		&i.Status,
		&i.TriggerType,
		&i.TriggeredBy,
		&i.JobName,
		&i.ErrorMessage,
		&i.RetryOf,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getGitRepository = `-- name: GetGitRepository :one
SELECT id, project_id, name, provider, clone_url, default_branch, dockerfile_path, build_context, image_repository, registry_credential, token_encrypted, webhook_secret_encrypted, auto_deploy, target_namespace, target_deployment, created_by, created_at, updated_at FROM git_repositories
WHERE project_id = $1 AND name = $2
LIMIT 1
`

type GetGitRepositoryParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
}

func (q *Queries) GetGitRepository(ctx context.Context, arg GetGitRepositoryParams) (GitRepository, error) {
	row := q.db.QueryRow(ctx, getGitRepository, arg.ProjectID, arg.Name)
	var i GitRepository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Provider,
		&i.CloneUrl,
		&i.DefaultBranch,
		&i.DockerfilePath,
		&i.BuildContext,
		&i.ImageRepository,
		&i.RegistryCredential,
		&i.TokenEncrypted,
		&i.WebhookSecretEncrypted,
		&i.AutoDeploy,
		&i.TargetNamespace,
		&i.TargetDeployment,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGitRepositoryByID = `-- name: GetGitRepositoryByID :one
SELECT id, project_id, name, provider, clone_url, default_branch, dockerfile_path, build_context, image_repository, registry_credential, token_encrypted, webhook_secret_encrypted, auto_deploy, target_namespace, target_deployment, created_by, created_at, updated_at FROM git_repositories WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGitRepositoryByID(ctx context.Context, id pgtype.UUID) (GitRepository, error) {
	row := q.db.QueryRow(ctx, getGitRepositoryByID, id)
	var i GitRepository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Provider,
		&i.CloneUrl,
		&i.DefaultBranch,
		&i.DockerfilePath,
		&i.BuildContext,
		&i.ImageRepository,
		&i.RegistryCredential,
		&i.TokenEncrypted,
		&i.WebhookSecretEncrypted,
		&i.AutoDeploy,
		&i.TargetNamespace,
		&i.TargetDeployment,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveBuilds = `-- name: ListActiveBuilds :many
SELECT id, repository_id, number, branch, commit_sha, image_tag, status, trigger_type, triggered_by, job_name, error_message, retry_of, started_at, finished_at, created_at FROM builds
WHERE status IN ('pending', 'running')
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListActiveBuilds(ctx context.Context, limit int32) ([]Build, error) {
	rows, err := q.db.Query(ctx, listActiveBuilds, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Build{}
	for rows.Next() {
		var i Build
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Number,
			&i.Branch,
			&i.CommitSha,
			&i.ImageTag,
			&i.Status,
			&i.TriggerType,
			&i.TriggeredBy,
			&i.JobName,
			&i.ErrorMessage,
			&i.RetryOf,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuilds = `-- name: ListBuilds :many
SELECT id, repository_id, number, branch, commit_sha, image_tag, status, trigger_type, triggered_by, job_name, error_message, retry_of, started_at, finished_at, created_at FROM builds
WHERE repository_id = $1
ORDER BY number DESC
LIMIT $3 OFFSET $2
`

type ListBuildsParams struct {
	RepositoryID pgtype.UUID `json:"repository_id"`
	Offset       int32       `json:"offset"`
	Limit        int32       `json:"limit"`
}

func (q *Queries) ListBuilds(ctx context.Context, arg ListBuildsParams) ([]Build, error) {
	rows, err := q.db.Query(ctx, listBuilds, arg.RepositoryID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Build{}
	for rows.Next() {
		var i Build
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Number,
			&i.Branch,
			&i.CommitSha,
			&i.ImageTag,
			&i.Status,
			&i.TriggerType,
			&i.TriggeredBy,
			&i.JobName,
			&i.ErrorMessage,
			&i.RetryOf,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitRepositories = `-- name: ListGitRepositories :many
SELECT id, project_id, name, provider, clone_url, default_branch, dockerfile_path, build_context, image_repository, registry_credential, token_encrypted, webhook_secret_encrypted, auto_deploy, target_namespace, target_deployment, created_by, created_at, updated_at FROM git_repositories
WHERE project_id = $1
ORDER BY name ASC
`

func (q *Queries) ListGitRepositories(ctx context.Context, projectID pgtype.UUID) ([]GitRepository, error) {
	rows, err := q.db.Query(ctx, listGitRepositories, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GitRepository{}
	for rows.Next() {
		var i GitRepository
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Provider,
			&i.CloneUrl,
			&i.DefaultBranch,
			&i.DockerfilePath,
			&i.BuildContext,
			&i.ImageRepository,
			&i.RegistryCredential,
			&i.TokenEncrypted,
			&i.WebhookSecretEncrypted,
			&i.AutoDeploy,
			&i.TargetNamespace,
			&i.TargetDeployment,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBuildRunning = `-- name: MarkBuildRunning :one
UPDATE builds
SET status = 'running', job_name = $2, started_at = COALESCE(started_at, NOW())
WHERE id = $1
RETURNING id, repository_id, number, branch, commit_sha, image_tag, status, trigger_type, triggered_by, job_name, error_message, retry_of, started_at, finished_at, created_at
`

type MarkBuildRunningParams struct {
	ID      pgtype.UUID `json:"id"`
	JobName string      `json:"job_name"`
}

func (q *Queries) MarkBuildRunning(ctx context.Context, arg MarkBuildRunningParams) (Build, error) {
	row := q.db.QueryRow(ctx, markBuildRunning, arg.ID, arg.JobName)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Number,
		&i.Branch,
		&i.CommitSha,
		&i.ImageTag,
		&i.Status,
		&i.TriggerType,
		&i.TriggeredBy,
		&i.JobName,
		&i.ErrorMessage,
		&i.RetryOf,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const setBuildCommit = `-- name: SetBuildCommit :exec
UPDATE builds SET commit_sha = $2, image_tag = $3 WHERE id = $1
`

type SetBuildCommitParams struct {
	ID        pgtype.UUID `json:"id"`
	CommitSha string      `json:"commit_sha"`
	ImageTag  string      `json:"image_tag"`
}

func (q *Queries) SetBuildCommit(ctx context.Context, arg SetBuildCommitParams) error {
	_, err := q.db.Exec(ctx, setBuildCommit, arg.ID, arg.CommitSha, arg.ImageTag)
	return err
}

const upsertGitRepository = `-- name: UpsertGitRepository :one
INSERT INTO git_repositories (
    project_id, name, provider, clone_url, default_branch,
    dockerfile_path, build_context, image_repository, registry_credential,
    token_encrypted, webhook_secret_encrypted,
    auto_deploy, target_namespace, target_deployment, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
ON CONFLICT (project_id, name) DO UPDATE
SET provider            = EXCLUDED.provider,
    clone_url           = EXCLUDED.clone_url,
    default_branch      = EXCLUDED.default_branch,
    dockerfile_path     = EXCLUDED.dockerfile_path,
    build_context       = EXCLUDED.build_context,
    image_repository    = EXCLUDED.image_repository,
    registry_credential = EXCLUDED.registry_credential,
    -- COALESCE keeps the stored secret when the caller sends none, so editing
    -- a repository does not require retyping a token the UI never received.
    token_encrypted          = COALESCE(EXCLUDED.token_encrypted, git_repositories.token_encrypted),
    webhook_secret_encrypted = COALESCE(EXCLUDED.webhook_secret_encrypted, git_repositories.webhook_secret_encrypted),
    auto_deploy         = EXCLUDED.auto_deploy,
    target_namespace    = EXCLUDED.target_namespace,
    target_deployment   = EXCLUDED.target_deployment,
    updated_at          = NOW()
RETURNING id, project_id, name, provider, clone_url, default_branch, dockerfile_path, build_context, image_repository, registry_credential, token_encrypted, webhook_secret_encrypted, auto_deploy, target_namespace, target_deployment, created_by, created_at, updated_at
`

type UpsertGitRepositoryParams struct {
	ProjectID              pgtype.UUID `json:"project_id"`
	Name                   string      `json:"name"`
	Provider               string      `json:"provider"`
	CloneUrl               string      `json:"clone_url"`
	DefaultBranch          string      `json:"default_branch"`
	DockerfilePath         string      `json:"dockerfile_path"`
	BuildContext           string      `json:"build_context"`
	ImageRepository        string      `json:"image_repository"`
	RegistryCredential     string      `json:"registry_credential"`
	TokenEncrypted         []byte      `json:"token_encrypted"`
	WebhookSecretEncrypted []byte      `json:"webhook_secret_encrypted"`
	AutoDeploy             bool        `json:"auto_deploy"`
	TargetNamespace        *string     `json:"target_namespace"`
	TargetDeployment       *string     `json:"target_deployment"`
	CreatedBy              string      `json:"created_by"`
}

func (q *Queries) UpsertGitRepository(ctx context.Context, arg UpsertGitRepositoryParams) (GitRepository, error) {
	row := q.db.QueryRow(ctx, upsertGitRepository,
		arg.ProjectID,
		arg.Name,
		arg.Provider,
		arg.CloneUrl,
		arg.DefaultBranch,
		arg.DockerfilePath,
		arg.BuildContext,
		arg.ImageRepository,
		arg.RegistryCredential,
		arg.TokenEncrypted,
		arg.WebhookSecretEncrypted,
		arg.AutoDeploy,
		arg.TargetNamespace,
		arg.TargetDeployment,
		arg.CreatedBy,
	)
	var i GitRepository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Provider,
		&i.CloneUrl,
		&i.DefaultBranch,
		&i.DockerfilePath,
		&i.BuildContext,
		&i.ImageRepository,
		&i.RegistryCredential,
		&i.TokenEncrypted,
		&i.WebhookSecretEncrypted,
		&i.AutoDeploy,
		&i.TargetNamespace,
		&i.TargetDeployment,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
