// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clusters.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearActiveCluster = `-- name: ClearActiveCluster :exec
UPDATE clusters
SET is_active  = FALSE,
    updated_at = NOW()
WHERE is_active = TRUE
`

func (q *Queries) ClearActiveCluster(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearActiveCluster)
	return err
}

const countClusters = `-- name: CountClusters :one
SELECT COUNT(*) FROM clusters
`

func (q *Queries) CountClusters(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countClusters)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCluster = `-- name: CreateCluster :one
INSERT INTO clusters (
    name, display_name, provider, status, kubeconfig_encrypted,
    server_url, kubernetes_version, node_count, is_active, last_error, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, name, display_name, provider, status, kubeconfig_encrypted, server_url, kubernetes_version, node_count, is_active, last_error, created_by, created_at, updated_at, cluster_uid
`

type CreateClusterParams struct {
	Name                string  `json:"name"`
	DisplayName         string  `json:"display_name"`
	Provider            string  `json:"provider"`
	Status              string  `json:"status"`
	KubeconfigEncrypted []byte  `json:"kubeconfig_encrypted"`
	ServerUrl           *string `json:"server_url"`
	KubernetesVersion   *string `json:"kubernetes_version"`
	NodeCount           int32   `json:"node_count"`
	IsActive            bool    `json:"is_active"`
	LastError           *string `json:"last_error"`
	CreatedBy           string  `json:"created_by"`
}

func (q *Queries) CreateCluster(ctx context.Context, arg CreateClusterParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, createCluster,
		arg.Name,
		arg.DisplayName,
		arg.Provider,
		arg.Status,
		arg.KubeconfigEncrypted,
		arg.ServerUrl,
		arg.KubernetesVersion,
		arg.NodeCount,
		arg.IsActive,
		arg.LastError,
		arg.CreatedBy,
	)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Provider,
		&i.Status,
		&i.KubeconfigEncrypted,
		&i.ServerUrl,
		&i.KubernetesVersion,
		&i.NodeCount,
		&i.IsActive,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClusterUid,
	)
	return i, err
}

const deleteCluster = `-- name: DeleteCluster :exec
DELETE FROM clusters
WHERE id = $1
`

func (q *Queries) DeleteCluster(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCluster, id)
	return err
}

const getActiveCluster = `-- name: GetActiveCluster :one
SELECT id, name, display_name, provider, status, kubeconfig_encrypted, server_url, kubernetes_version, node_count, is_active, last_error, created_by, created_at, updated_at, cluster_uid FROM clusters
WHERE is_active = TRUE
LIMIT 1
`

func (q *Queries) GetActiveCluster(ctx context.Context) (Cluster, error) {
	row := q.db.QueryRow(ctx, getActiveCluster)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Provider,
		&i.Status,
		&i.KubeconfigEncrypted,
		&i.ServerUrl,
		&i.KubernetesVersion,
		&i.NodeCount,
		&i.IsActive,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClusterUid,
	)
	return i, err
}

const getCluster = `-- name: GetCluster :one
SELECT id, name, display_name, provider, status, kubeconfig_encrypted, server_url, kubernetes_version, node_count, is_active, last_error, created_by, created_at, updated_at, cluster_uid FROM clusters
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCluster(ctx context.Context, id pgtype.UUID) (Cluster, error) {
	row := q.db.QueryRow(ctx, getCluster, id)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Provider,
		&i.Status,
		&i.KubeconfigEncrypted,
		&i.ServerUrl,
		&i.KubernetesVersion,
		&i.NodeCount,
		&i.IsActive,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClusterUid,
	)
	return i, err
}

const getClusterByName = `-- name: GetClusterByName :one
SELECT id, name, display_name, provider, status, kubeconfig_encrypted, server_url, kubernetes_version, node_count, is_active, last_error, created_by, created_at, updated_at, cluster_uid FROM clusters
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetClusterByName(ctx context.Context, name string) (Cluster, error) {
	row := q.db.QueryRow(ctx, getClusterByName, name)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Provider,
		&i.Status,
		&i.KubeconfigEncrypted,
		&i.ServerUrl,
		&i.KubernetesVersion,
		&i.NodeCount,
		&i.IsActive,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClusterUid,
	)
	return i, err
}

const listClusters = `-- name: ListClusters :many
SELECT id, name, display_name, provider, status, kubeconfig_encrypted, server_url, kubernetes_version, node_count, is_active, last_error, created_by, created_at, updated_at, cluster_uid FROM clusters
ORDER BY is_active DESC, created_at ASC
`

func (q *Queries) ListClusters(ctx context.Context) ([]Cluster, error) {
	rows, err := q.db.Query(ctx, listClusters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cluster{}
	for rows.Next() {
		var i Cluster
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Provider,
			&i.Status,
			&i.KubeconfigEncrypted,
			&i.ServerUrl,
			&i.KubernetesVersion,
			&i.NodeCount,
			&i.IsActive,
			&i.LastError,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClusterUid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setClusterActive = `-- name: SetClusterActive :one
UPDATE clusters
SET is_active  = TRUE,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, display_name, provider, status, kubeconfig_encrypted, server_url, kubernetes_version, node_count, is_active, last_error, created_by, created_at, updated_at, cluster_uid
`

func (q *Queries) SetClusterActive(ctx context.Context, id pgtype.UUID) (Cluster, error) {
	row := q.db.QueryRow(ctx, setClusterActive, id)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Provider,
		&i.Status,
		&i.KubeconfigEncrypted,
		&i.ServerUrl,
		&i.KubernetesVersion,
		&i.NodeCount,
		&i.IsActive,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClusterUid,
	)
	return i, err
}

const setClusterIdentity = `-- name: SetClusterIdentity :one
UPDATE clusters
SET cluster_uid = $2,
    updated_at  = NOW()
WHERE id = $1
RETURNING id, name, display_name, provider, status, kubeconfig_encrypted, server_url, kubernetes_version, node_count, is_active, last_error, created_by, created_at, updated_at, cluster_uid
`

type SetClusterIdentityParams struct {
	ID         pgtype.UUID `json:"id"`
	ClusterUid *string     `json:"cluster_uid"`
}

// Records which physical cluster answers behind this row. Written after a
// successful connect, so a later mismatch is evidence the cluster was rebuilt.
func (q *Queries) SetClusterIdentity(ctx context.Context, arg SetClusterIdentityParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, setClusterIdentity, arg.ID, arg.ClusterUid)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Provider,
		&i.Status,
		&i.KubeconfigEncrypted,
		&i.ServerUrl,
		&i.KubernetesVersion,
		&i.NodeCount,
		&i.IsActive,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClusterUid,
	)
	return i, err
}

const setClusterProvider = `-- name: SetClusterProvider :one
UPDATE clusters
SET provider   = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, display_name, provider, status, kubeconfig_encrypted, server_url, kubernetes_version, node_count, is_active, last_error, created_by, created_at, updated_at, cluster_uid
`

type SetClusterProviderParams struct {
	ID       pgtype.UUID `json:"id"`
	Provider string      `json:"provider"`
}

// Corrects a row whose provider was recorded wrongly. Only used to reclassify
// a locally provisioned cluster that was seeded as 'imported', which left its
// lifecycle inert: stop merely disconnected and delete only removed the row.
func (q *Queries) SetClusterProvider(ctx context.Context, arg SetClusterProviderParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, setClusterProvider, arg.ID, arg.Provider)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Provider,
		&i.Status,
		&i.KubeconfigEncrypted,
		&i.ServerUrl,
		&i.KubernetesVersion,
		&i.NodeCount,
		&i.IsActive,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClusterUid,
	)
	return i, err
}

const updateClusterRuntime = `-- name: UpdateClusterRuntime :one
UPDATE clusters
SET kubeconfig_encrypted = $2,
    server_url           = $3,
    kubernetes_version   = $4,
    node_count           = $5,
    status               = $6,
    last_error           = $7,
    updated_at           = NOW()
WHERE id = $1
RETURNING id, name, display_name, provider, status, kubeconfig_encrypted, server_url, kubernetes_version, node_count, is_active, last_error, created_by, created_at, updated_at, cluster_uid
`

type UpdateClusterRuntimeParams struct {
	ID                  pgtype.UUID `json:"id"`
	KubeconfigEncrypted []byte      `json:"kubeconfig_encrypted"`
	ServerUrl           *string     `json:"server_url"`
	KubernetesVersion   *string     `json:"kubernetes_version"`
	NodeCount           int32       `json:"node_count"`
	Status              string      `json:"status"`
	LastError           *string     `json:"last_error"`
}

func (q *Queries) UpdateClusterRuntime(ctx context.Context, arg UpdateClusterRuntimeParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, updateClusterRuntime,
		arg.ID,
		arg.KubeconfigEncrypted,
		arg.ServerUrl,
		arg.KubernetesVersion,
		arg.NodeCount,
		arg.Status,
		arg.LastError,
	)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Provider,
		&i.Status,
		&i.KubeconfigEncrypted,
		&i.ServerUrl,
		&i.KubernetesVersion,
		&i.NodeCount,
		&i.IsActive,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClusterUid,
	)
	return i, err
}

const updateClusterStatus = `-- name: UpdateClusterStatus :one
UPDATE clusters
SET status     = $2,
    last_error = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, display_name, provider, status, kubeconfig_encrypted, server_url, kubernetes_version, node_count, is_active, last_error, created_by, created_at, updated_at, cluster_uid
`

type UpdateClusterStatusParams struct {
	ID        pgtype.UUID `json:"id"`
	Status    string      `json:"status"`
	LastError *string     `json:"last_error"`
}

func (q *Queries) UpdateClusterStatus(ctx context.Context, arg UpdateClusterStatusParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, updateClusterStatus, arg.ID, arg.Status, arg.LastError)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Provider,
		&i.Status,
		&i.KubeconfigEncrypted,
		&i.ServerUrl,
		&i.KubernetesVersion,
		&i.NodeCount,
		&i.IsActive,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClusterUid,
	)
	return i, err
}
