// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       string             `json:"user_id"`
	UserEmail    string             `json:"user_email"`
	Action       string             `json:"action"`
	Namespace    *string            `json:"namespace"`
	Resource     *string            `json:"resource"`
	ResourceType *string            `json:"resource_type"`
	Result       string             `json:"result"`
	Details      []byte             `json:"details"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Build struct {
	ID           pgtype.UUID        `json:"id"`
	RepositoryID pgtype.UUID        `json:"repository_id"`
	Number       int64              `json:"number"`
	Branch       string             `json:"branch"`
	CommitSha    string             `json:"commit_sha"`
	ImageTag     string             `json:"image_tag"`
	Status       string             `json:"status"`
	TriggerType  string             `json:"trigger_type"`
	TriggeredBy  string             `json:"triggered_by"`
	JobName      string             `json:"job_name"`
	ErrorMessage *string            `json:"error_message"`
	RetryOf      pgtype.UUID        `json:"retry_of"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Cluster struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	DisplayName         string             `json:"display_name"`
	Provider            string             `json:"provider"`
	Status              string             `json:"status"`
	KubeconfigEncrypted []byte             `json:"kubeconfig_encrypted"`
	ServerUrl           *string            `json:"server_url"`
	KubernetesVersion   *string            `json:"kubernetes_version"`
	NodeCount           int32              `json:"node_count"`
	IsActive            bool               `json:"is_active"`
	LastError           *string            `json:"last_error"`
	CreatedBy           string             `json:"created_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ClusterUid          *string            `json:"cluster_uid"`
}

type GitRepository struct {
	ID                     pgtype.UUID        `json:"id"`
	ProjectID              pgtype.UUID        `json:"project_id"`
	Name                   string             `json:"name"`
	Provider               string             `json:"provider"`
	CloneUrl               string             `json:"clone_url"`
	DefaultBranch          string             `json:"default_branch"`
	DockerfilePath         string             `json:"dockerfile_path"`
	BuildContext           string             `json:"build_context"`
	ImageRepository        string             `json:"image_repository"`
	RegistryCredential     string             `json:"registry_credential"`
	TokenEncrypted         []byte             `json:"token_encrypted"`
	WebhookSecretEncrypted []byte             `json:"webhook_secret_encrypted"`
	AutoDeploy             bool               `json:"auto_deploy"`
	TargetNamespace        *string            `json:"target_namespace"`
	TargetDeployment       *string            `json:"target_deployment"`
	CreatedBy              string             `json:"created_by"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type Namespace struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	DisplayName string             `json:"display_name"`
	Description *string            `json:"description"`
	OwnerID     string             `json:"owner_id"`
	OwnerEmail  string             `json:"owner_email"`
	Labels      []byte             `json:"labels"`
	Annotations []byte             `json:"annotations"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	ClusterUid  *string            `json:"cluster_uid"`
}

type Project struct {
	ID          pgtype.UUID        `json:"id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	OwnerID     string             `json:"owner_id"`
	OwnerEmail  string             `json:"owner_email"`
	Labels      []byte             `json:"labels"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ProjectMember struct {
	ProjectID pgtype.UUID        `json:"project_id"`
	UserID    string             `json:"user_id"`
	UserEmail string             `json:"user_email"`
	Role      string             `json:"role"`
	AddedAt   pgtype.Timestamptz `json:"added_at"`
}

type RegistryCredential struct {
	ID                pgtype.UUID        `json:"id"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	Name              string             `json:"name"`
	RegistryUrl       string             `json:"registry_url"`
	Username          string             `json:"username"`
	PasswordEncrypted []byte             `json:"password_encrypted"`
	Email             *string            `json:"email"`
	CreatedBy         string             `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
