// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: namespaces.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNamespaces = `-- name: CountNamespaces :one
SELECT COUNT(*)
FROM namespaces
WHERE status != 'deleted'
    AND ($1::text IS NULL OR status = $1)
    AND ($2::text IS NULL OR owner_email = $2)
`

type CountNamespacesParams struct {
	Status     *string `json:"status"`
	OwnerEmail *string `json:"owner_email"`
}

func (q *Queries) CountNamespaces(ctx context.Context, arg CountNamespacesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNamespaces, arg.Status, arg.OwnerEmail)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNamespace = `-- name: CreateNamespace :one
INSERT INTO namespaces (
    name,
    display_name,
    description,
    owner_id,
    owner_email,
    labels,
    annotations,
    status,
    project_id,
    cluster_uid
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, name, display_name, description, owner_id, owner_email, labels, annotations, status, created_at, updated_at, project_id, cluster_uid
`

type CreateNamespaceParams struct {
	Name        string      `json:"name"`
	DisplayName string      `json:"display_name"`
	Description *string     `json:"description"`
	OwnerID     string      `json:"owner_id"`
	OwnerEmail  string      `json:"owner_email"`
	Labels      []byte      `json:"labels"`
	Annotations []byte      `json:"annotations"`
	Status      string      `json:"status"`
	ProjectID   pgtype.UUID `json:"project_id"`
	ClusterUid  *string     `json:"cluster_uid"`
}

func (q *Queries) CreateNamespace(ctx context.Context, arg CreateNamespaceParams) (Namespace, error) {
	row := q.db.QueryRow(ctx, createNamespace,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.OwnerID,
		arg.OwnerEmail,
		arg.Labels,
		arg.Annotations,
		arg.Status,
		arg.ProjectID,
		arg.ClusterUid,
	)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.OwnerID,
		&i.OwnerEmail,
		&i.Labels,
		&i.Annotations,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.ClusterUid,
	)
	return i, err
}

const deleteNamespace = `-- name: DeleteNamespace :exec
UPDATE namespaces
SET status = 'deleted', updated_at = NOW()
WHERE name = $1
`

func (q *Queries) DeleteNamespace(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteNamespace, name)
	return err
}

const getNamespaceByName = `-- name: GetNamespaceByName :one
SELECT id, name, display_name, description, owner_id, owner_email, labels, annotations, status, created_at, updated_at, project_id, cluster_uid FROM namespaces
WHERE name = $1 AND status != 'deleted'
LIMIT 1
`

func (q *Queries) GetNamespaceByName(ctx context.Context, name string) (Namespace, error) {
	row := q.db.QueryRow(ctx, getNamespaceByName, name)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.OwnerID,
		&i.OwnerEmail,
		&i.Labels,
		&i.Annotations,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.ClusterUid,
	)
	return i, err
}

const listNamespaces = `-- name: ListNamespaces :many
SELECT id, name, display_name, description, owner_id, owner_email, labels, annotations, status, created_at, updated_at, project_id, cluster_uid
FROM namespaces
WHERE status != 'deleted'
    AND ($1::text IS NULL OR status = $1)
    AND ($2::text IS NULL OR owner_email = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListNamespacesParams struct {
	Status     *string `json:"status"`
	OwnerEmail *string `json:"owner_email"`
	Offset     int32   `json:"offset"`
	Limit      int32   `json:"limit"`
}

func (q *Queries) ListNamespaces(ctx context.Context, arg ListNamespacesParams) ([]Namespace, error) {
	rows, err := q.db.Query(ctx, listNamespaces,
		arg.Status,
		arg.OwnerEmail,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Namespace{}
	for rows.Next() {
		var i Namespace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.OwnerID,
			&i.OwnerEmail,
			&i.Labels,
			&i.Annotations,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
			&i.ClusterUid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNamespacesByProject = `-- name: ListNamespacesByProject :many
SELECT id, name, display_name, description, owner_id, owner_email, labels, annotations, status, created_at, updated_at, project_id, cluster_uid FROM namespaces
WHERE project_id = $1 AND status != 'deleted'
ORDER BY name ASC
`

func (q *Queries) ListNamespacesByProject(ctx context.Context, projectID pgtype.UUID) ([]Namespace, error) {
	rows, err := q.db.Query(ctx, listNamespacesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Namespace{}
	for rows.Next() {
		var i Namespace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.OwnerID,
			&i.OwnerEmail,
			&i.Labels,
			&i.Annotations,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
			&i.ClusterUid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orphanNamespacesFromOtherClusters = `-- name: OrphanNamespacesFromOtherClusters :many
UPDATE namespaces
SET status = 'deleted', updated_at = NOW()
WHERE status != 'deleted'
    AND cluster_uid IS NOT NULL
    AND cluster_uid != $1
RETURNING name
`

// Retires namespace records belonging to a cluster that no longer exists.
//
// Called when a reconnect proves the cluster behind a fleet row was rebuilt:
// every namespace provisioned into the old cluster died with it.
func (q *Queries) OrphanNamespacesFromOtherClusters(ctx context.Context, clusterUid *string) ([]string, error) {
	rows, err := q.db.Query(ctx, orphanNamespacesFromOtherClusters, clusterUid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireNamespacesOfCluster = `-- name: RetireNamespacesOfCluster :many
UPDATE namespaces
SET status = 'deleted', updated_at = NOW()
WHERE status != 'deleted'
    AND cluster_uid = $1
RETURNING name
`

// Retires every namespace that was adopted onto a specific cluster. Used when
// that cluster is deleted, so a later recreation does not inherit its records.
func (q *Queries) RetireNamespacesOfCluster(ctx context.Context, clusterUid *string) ([]string, error) {
	rows, err := q.db.Query(ctx, retireNamespacesOfCluster, clusterUid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireUnprovenancedNamespaces = `-- name: RetireUnprovenancedNamespaces :many
UPDATE namespaces
SET status = 'deleted', updated_at = NOW()
WHERE status != 'deleted'
    AND cluster_uid IS NULL
RETURNING name
`

// Retires namespace rows that were never fingerprinted. Safe only when the
// caller already knows the live cluster is new (rebuild or last-cluster delete):
// those rows cannot be proven to belong to it, and leaving them is how deleted
// namespaces kept appearing after a recreate.
func (q *Queries) RetireUnprovenancedNamespaces(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, retireUnprovenancedNamespaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNamespaceClusterUID = `-- name: SetNamespaceClusterUID :exec
UPDATE namespaces
SET cluster_uid = $2, updated_at = NOW()
WHERE name = $1 AND status != 'deleted'
`

type SetNamespaceClusterUIDParams struct {
	Name       string  `json:"name"`
	ClusterUid *string `json:"cluster_uid"`
}

// Backfills provenance for a namespace confirmed to exist in the live cluster.
// Rows created before identity tracking, and rows adopted after a reconnect,
// both land here.
func (q *Queries) SetNamespaceClusterUID(ctx context.Context, arg SetNamespaceClusterUIDParams) error {
	_, err := q.db.Exec(ctx, setNamespaceClusterUID, arg.Name, arg.ClusterUid)
	return err
}

const setNamespaceProject = `-- name: SetNamespaceProject :one
UPDATE namespaces
SET project_id = $2, updated_at = NOW()
WHERE name = $1 AND status != 'deleted'
RETURNING id, name, display_name, description, owner_id, owner_email, labels, annotations, status, created_at, updated_at, project_id, cluster_uid
`

type SetNamespaceProjectParams struct {
	Name      string      `json:"name"`
	ProjectID pgtype.UUID `json:"project_id"`
}

// Attaches an existing namespace to a project so credential and config
// lookups can resolve namespace -> project.
func (q *Queries) SetNamespaceProject(ctx context.Context, arg SetNamespaceProjectParams) (Namespace, error) {
	row := q.db.QueryRow(ctx, setNamespaceProject, arg.Name, arg.ProjectID)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.OwnerID,
		&i.OwnerEmail,
		&i.Labels,
		&i.Annotations,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.ClusterUid,
	)
	return i, err
}

const updateNamespaceStatus = `-- name: UpdateNamespaceStatus :one
UPDATE namespaces
SET status = $2, updated_at = NOW()
WHERE name = $1
RETURNING id, name, display_name, description, owner_id, owner_email, labels, annotations, status, created_at, updated_at, project_id, cluster_uid
`

type UpdateNamespaceStatusParams struct {
	Name   string `json:"name"`
	Status string `json:"status"`
}

func (q *Queries) UpdateNamespaceStatus(ctx context.Context, arg UpdateNamespaceStatusParams) (Namespace, error) {
	row := q.db.QueryRow(ctx, updateNamespaceStatus, arg.Name, arg.Status)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.OwnerID,
		&i.OwnerEmail,
		&i.Labels,
		&i.Annotations,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.ClusterUid,
	)
	return i, err
}
