// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectMember = `-- name: AddProjectMember :one
INSERT INTO project_members (project_id, user_id, user_email, role)
VALUES ($1, $2, $3, $4)
ON CONFLICT (project_id, user_email)
DO UPDATE SET role = EXCLUDED.role
RETURNING project_id, user_id, user_email, role, added_at
`

type AddProjectMemberParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    string      `json:"user_id"`
	UserEmail string      `json:"user_email"`
	Role      string      `json:"role"`
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, addProjectMember,
		arg.ProjectID,
		arg.UserID,
		arg.UserEmail,
		arg.Role,
	)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.UserEmail,
		&i.Role,
		&i.AddedAt,
	)
	return i, err
}

const countProjectMembers = `-- name: CountProjectMembers :one
SELECT COUNT(*) FROM project_members WHERE project_id = $1
`

func (q *Queries) CountProjectMembers(ctx context.Context, projectID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectMembers, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjectNamespaces = `-- name: CountProjectNamespaces :one
SELECT COUNT(*) FROM namespaces
WHERE project_id = $1 AND status != 'deleted'
`

func (q *Queries) CountProjectNamespaces(ctx context.Context, projectID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectNamespaces, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*) FROM projects WHERE status != 'deleted'
`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjectsForMember = `-- name: CountProjectsForMember :one
SELECT COUNT(DISTINCT p.id) FROM projects p
LEFT JOIN project_members m ON m.project_id = p.id
WHERE p.status != 'deleted'
  AND (p.owner_email = $1 OR m.user_email = $1)
`

func (q *Queries) CountProjectsForMember(ctx context.Context, userEmail string) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectsForMember, userEmail)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (slug, name, description, owner_id, owner_email, labels, status)
VALUES ($1, $2, $3, $4, $5, $6, 'active')
RETURNING id, slug, name, description, owner_id, owner_email, labels, status, created_at, updated_at
`

type CreateProjectParams struct {
	Slug        string  `json:"slug"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	OwnerID     string  `json:"owner_id"`
	OwnerEmail  string  `json:"owner_email"`
	Labels      []byte  `json:"labels"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.OwnerEmail,
		arg.Labels,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.OwnerEmail,
		&i.Labels,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
UPDATE projects
SET status = 'deleted', updated_at = NOW()
WHERE slug = $1
`

func (q *Queries) DeleteProject(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deleteProject, slug)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, slug, name, description, owner_id, owner_email, labels, status, created_at, updated_at FROM projects
WHERE id = $1 AND status != 'deleted'
LIMIT 1
`

func (q *Queries) GetProjectByID(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.OwnerEmail,
		&i.Labels,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, slug, name, description, owner_id, owner_email, labels, status, created_at, updated_at FROM projects
WHERE slug = $1 AND status != 'deleted'
LIMIT 1
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.OwnerEmail,
		&i.Labels,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT project_id, user_id, user_email, role, added_at FROM project_members
WHERE project_id = $1 AND user_email = $2
LIMIT 1
`

type GetProjectMemberParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserEmail string      `json:"user_email"`
}

func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, getProjectMember, arg.ProjectID, arg.UserEmail)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.UserEmail,
		&i.Role,
		&i.AddedAt,
	)
	return i, err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT project_id, user_id, user_email, role, added_at FROM project_members
WHERE project_id = $1
ORDER BY added_at ASC
`

func (q *Queries) ListProjectMembers(ctx context.Context, projectID pgtype.UUID) ([]ProjectMember, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectMember{}
	for rows.Next() {
		var i ProjectMember
		if err := rows.Scan(
			&i.ProjectID,
			&i.UserID,
			&i.UserEmail,
			&i.Role,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, slug, name, description, owner_id, owner_email, labels, status, created_at, updated_at FROM projects
WHERE status != 'deleted'
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListProjectsParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.OwnerEmail,
			&i.Labels,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForMember = `-- name: ListProjectsForMember :many
SELECT p.id, p.slug, p.name, p.description, p.owner_id, p.owner_email, p.labels, p.status, p.created_at, p.updated_at FROM projects p
LEFT JOIN project_members m ON m.project_id = p.id
WHERE p.status != 'deleted'
  AND (p.owner_email = $1 OR m.user_email = $1)
GROUP BY p.id
ORDER BY p.created_at DESC
LIMIT $3 OFFSET $2
`

type ListProjectsForMemberParams struct {
	UserEmail string `json:"user_email"`
	Offset    int32  `json:"offset"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) ListProjectsForMember(ctx context.Context, arg ListProjectsForMemberParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsForMember, arg.UserEmail, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.OwnerEmail,
			&i.Labels,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectMember = `-- name: RemoveProjectMember :exec
DELETE FROM project_members
WHERE project_id = $1 AND user_email = $2
`

type RemoveProjectMemberParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserEmail string      `json:"user_email"`
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error {
	_, err := q.db.Exec(ctx, removeProjectMember, arg.ProjectID, arg.UserEmail)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $2,
    description = $3,
    labels = $4,
    updated_at = NOW()
WHERE slug = $1
RETURNING id, slug, name, description, owner_id, owner_email, labels, status, created_at, updated_at
`

type UpdateProjectParams struct {
	Slug        string  `json:"slug"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Labels      []byte  `json:"labels"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Labels,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.OwnerEmail,
		&i.Labels,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
