// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registry.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRegistryCredential = `-- name: DeleteRegistryCredential :exec
DELETE FROM registry_credentials
WHERE project_id = $1 AND name = $2
`

type DeleteRegistryCredentialParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
}

func (q *Queries) DeleteRegistryCredential(ctx context.Context, arg DeleteRegistryCredentialParams) error {
	_, err := q.db.Exec(ctx, deleteRegistryCredential, arg.ProjectID, arg.Name)
	return err
}

const getRegistryCredential = `-- name: GetRegistryCredential :one
SELECT id, project_id, name, registry_url, username, password_encrypted, email, created_by, created_at, updated_at FROM registry_credentials
WHERE project_id = $1 AND name = $2
LIMIT 1
`

type GetRegistryCredentialParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
}

func (q *Queries) GetRegistryCredential(ctx context.Context, arg GetRegistryCredentialParams) (RegistryCredential, error) {
	row := q.db.QueryRow(ctx, getRegistryCredential, arg.ProjectID, arg.Name)
	var i RegistryCredential
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.RegistryUrl,
		&i.Username,
		&i.PasswordEncrypted,
		&i.Email,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRegistryCredentials = `-- name: ListRegistryCredentials :many
SELECT id, project_id, name, registry_url, username, password_encrypted, email, created_by, created_at, updated_at FROM registry_credentials
WHERE project_id = $1
ORDER BY name ASC
`

func (q *Queries) ListRegistryCredentials(ctx context.Context, projectID pgtype.UUID) ([]RegistryCredential, error) {
	rows, err := q.db.Query(ctx, listRegistryCredentials, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RegistryCredential{}
	for rows.Next() {
		var i RegistryCredential
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.RegistryUrl,
			&i.Username,
			&i.PasswordEncrypted,
			&i.Email,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRegistryCredential = `-- name: UpsertRegistryCredential :one
INSERT INTO registry_credentials (
    project_id, name, registry_url, username, password_encrypted, email, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (project_id, name) DO UPDATE
SET registry_url       = EXCLUDED.registry_url,
    username           = EXCLUDED.username,
    password_encrypted = EXCLUDED.password_encrypted,
    email              = EXCLUDED.email,
    updated_at         = NOW()
RETURNING id, project_id, name, registry_url, username, password_encrypted, email, created_by, created_at, updated_at
`

type UpsertRegistryCredentialParams struct {
	ProjectID         pgtype.UUID `json:"project_id"`
	Name              string      `json:"name"`
	RegistryUrl       string      `json:"registry_url"`
	Username          string      `json:"username"`
	PasswordEncrypted []byte      `json:"password_encrypted"`
	Email             *string     `json:"email"`
	CreatedBy         string      `json:"created_by"`
}

func (q *Queries) UpsertRegistryCredential(ctx context.Context, arg UpsertRegistryCredentialParams) (RegistryCredential, error) {
	row := q.db.QueryRow(ctx, upsertRegistryCredential,
		arg.ProjectID,
		arg.Name,
		arg.RegistryUrl,
		arg.Username,
		arg.PasswordEncrypted,
		arg.Email,
		arg.CreatedBy,
	)
	var i RegistryCredential
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.RegistryUrl,
		&i.Username,
		&i.PasswordEncrypted,
		&i.Email,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
